### ISSUE TITLE
As a Front End Developer, must create a welcoming page

### ISSUE THREAD

**Issue by MuhammadZabir** [MuhammadZabir/HotelRating#1]
This would be the main page. Try design and ask everyone's opinion before pushing

**Comment by mhmdsyahmi** [comment]
Hi guys just noticed something for searching page.. the UI I think is not dynamic (not responsive) meaning that the size is fix. If the users access the system with different screen size then it will be a problem. try to use bootstrap framework or search on how to make JSP UI presentation responsive .
@muhaafidz4ever , @afiqzamanhuri , @arcmal
